export const chatgptThemeDark = {
  'code[class*="language-"]': {
    color: "#e5e7eb",
    background: "#0d1117",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontSize: "13.5px",
    lineHeight: "1.6",
  },
  'pre[class*="language-"]': {
    color: "#e5e7eb",
    background: "#0d1117",
    margin: 0,
    padding: "16px",
    overflow: "auto",
  },
  comment: { color: "#6b7280" },
  prolog: { color: "#6b7280" },
  doctype: { color: "#6b7280" },
  cdata: { color: "#6b7280" },
  punctuation: { color: "#9ca3af" },
  property: { color: "#f87171" },
  tag: { color: "#f87171" },
  boolean: { color: "#f87171" },
  number: { color: "#f87171" },
  constant: { color: "#f87171" },
  selector: { color: "#34d399" },
  attrName: { color: "#34d399" },
  string: { color: "#34d399" },
  char: { color: "#34d399" },
  builtin: { color: "#34d399" },
  operator: { color: "#9ca3af" },
  entity: { color: "#9ca3af" },
  url: { color: "#60a5fa" },
  function: { color: "#60a5fa" },
  keyword: { color: "#c084fc" },
  regex: { color: "#fbbf24" },
  important: { color: "#fbbf24" },
};

export const chatgptThemeLight = {
  'code[class*="language-"]': {
    color: "#111827",
    background: "#ffffff",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontSize: "13.5px",
    lineHeight: "1.6",
  },
  'pre[class*="language-"]': {
    color: "#111827",
    background: "#ffffff",
    margin: 0,
    padding: "16px",
    overflow: "auto",
  },
  comment: { color: "#6b7280" },
  punctuation: { color: "#374151" },
  property: { color: "#dc2626" },
  tag: { color: "#dc2626" },
  boolean: { color: "#dc2626" },
  number: { color: "#dc2626" },
  constant: { color: "#dc2626" },
  selector: { color: "#059669" },
  attrName: { color: "#059669" },
  string: { color: "#059669" },
  char: { color: "#059669" },
  builtin: { color: "#059669" },
  operator: { color: "#374151" },
  function: { color: "#2563eb" },
  keyword: { color: "#7c3aed" },
  regex: { color: "#d97706" },
};

// A helper to switch between them
export const chatgptThemes = {
    dark: chatgptThemeDark,
    light: chatgptThemeLight
};