import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../node_modules/react-pings/dist/index.css";
import "./globals.css";
import PingsProvider from "@/components/pings-provider";
import { Navbar } from "@/components";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`bg-background text-foreground ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full w-full" cz-shortcut-listen="true">
        <ThemeProvider attribute={"class"} defaultTheme="system" enableSystem>
          <Navbar />
          <PingsProvider>{children}</PingsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
